name: New version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-new-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-tags: true

      - name: Install dependencies
        run: npm install --immutable

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{version}}
          git-tag-version: 'true'

      # - name: Create version & update CHANGELOG
      #   run: |
      #     npm version ${{ inputs.version }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "${{ github.head_ref }}"
